### ISSUE TITLE
Map::setNode(): Not allowing to place CONTENT_IGNORE while trying to replace "trail:dirt_with_snow"

### ISSUE THREAD

**Issue by diogogomes** [paramat/trail#4]
**Minetest:** 0.4.15
**Trail:** Unversioned (master)

`ERROR[Server]: Map::setNode(): Not allowing to place CONTENT_IGNORE while trying to replace "trail:dirt_with_snow" at (0,7,-69) (block (0,0,-5))`

**Comment by paramat** [comment]
Probably fixed by 64911857a6da05d1d2bb9277fb145a9048065949
